### PR TITLE
BSCM inclusion and alternative RSAT url and file names

### PR DESCRIPTION
**Pull request by sdanzige**
This version includes the background sampled coherence metric (BSCM), (Danziger, Ratusny, Plaisier, et al.. 2015 BMC Systems Biology).  It also allows querying alternative RSAT depositories and files, which is useful for organisms such as Human and Mouse.

### CODE REVIEW

**Comment by sdanzige** [comment]
Thank you.

On Wed, Feb 4, 2015 at 10:50 AM, Wei-ju Wu <notifications@github.com> wrote:

> Merged #41 <https://github.com/baliga-lab/cmonkey2/pull/41>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baliga-lab/cmonkey2/pull/41#event-230252442>.
>



-- 
Samuel A. Danziger, PhD
Biomedical Engineering
Sam_Danziger@ieee.org
(908)246-4502
http://samdanziger.com/

Truth Cannot Contradict Truth

**Comment by weiju** [comment]
Hi Sam,
for some reason your commits removed the testdata/RSAT_genomes_listing.txt file, which breaks the unit test suite. I have put the file back into the repository. Please make sure the unit test suite runs successfully before creating a merge request next time.
Thanks,
Wei-ju

**Comment by sdanzige** [comment]
Wei-ju,

Sorry about that.  I don't know why it happened.  The file is still there
so I must have un-indexed it somehow.

-Sam

On Wed, Feb 4, 2015 at 11:00 AM, Wei-ju Wu <notifications@github.com> wrote:

> Hi Sam,
> for some reason your commits removed the testdata/RSAT_genomes_listing.txt
> file, which breaks the unit test suite. I have put the file back into the
> repository. Please make sure the unit test suite runs successfully before
> creating a merge request next time.
> Thanks,
> Wei-ju
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baliga-lab/cmonkey2/pull/41#issuecomment-72915929>.
>



-- 
Samuel A. Danziger, PhD
Biomedical Engineering
Sam_Danziger@ieee.org
(908)246-4502
http://samdanziger.com/

Truth Cannot Contradict Truth

**Comment by sdanzige** [comment]
Wei-ju,

When I pull the latest version and run the test suite in linux I get the
following errors:

Can you please help me to debug?

Thanks,
-Sam

test_motif_scoring (meme430_test.Meme430Test)
tests the motif scoring in integration ... WARNING:root:dropped operon from
network (max_operon_size exceeded): ['VNG1688C', 'VNG1689G', 'VNG1690G',
'VNG1691G', 'VNG1692G', 'VNG1693G', 'VNG1695G', 'VNG1697G', 'VNG1698G',
'VNG1699C', 'VNG1700G', 'VNG1701G', 'VNG1702G', 'VNG1703G', 'VNG1705G',
'VNG1706G', 'VNG1707G', 'VNG1709G', 'VNG1711G', 'VNG1713G', 'VNG1714G',
'VNG1715G', 'VNG1716G', 'VNG1718G', 'VNG1719G']
WARNING:root:25 genes not found in synonyms.
Unknown error in MAST:
  {'cmd': ['mast', '/tmp/meme.out.JIecJE', '-d', '/tmp/memeseqs56aAP5',
'-bfile', '/tmp/memebgf1dj5o', '-nostatus', '-stdout', '-text', '-brief',
'-ev', '999999', '-mev', '9999999', '-mt', '0.99', '-seqp', '-remcorr'],
'output': 'error at: -d\n\nUSAGE:\n\tmast\t<motif file> <sequence file>
[options] \n\t[-bfile <bf>]\tread background frequencies from
<bf>\n\t[-dblist]\tthe file specified as database contains a list of
databases\n\t[-o <dir>]\tdirectory to output mast results\n\t[-oc
<dir>]\tdirectory to output mast results with overwriting
allowed\n\t[-hit_list]\tprint only a list of non-overlapping hits to
stdout\n\t[-remcorr]\tremove highly correlated motifs from query\n\t[-m
<m>]+\tuse only motif(s) number <m> (overrides -mev)\n\t[-c <count>]\tonly
use the first <count> motifs or all motifs when <count> is zero (default:
0)\n\t[-mev <mev>]+\tuse only motifs with E-values less than
<mev>\n\t[-diag <diag>]\tnominal order and spacing of
motifs\n\t[-norc]\t\tdo not score reverse complement DNA
strand\n\t[-sep]\t\tscore reverse complement DNA strand as a separate
\n\t\t\tsequence\n\t[-dna]\t\ttranslate DNA sequences to
protein\n\t[-comp]\t\tadjust p-values and E-values for sequence
composition\n\t[-ev <ev>]\tprint results for sequences with E-value <
<ev>\n\t\t\t(default: 10)\n\t[-mt <mt>]\tshow motif matches with p-value <
mt (default: 0.0001)\n\t[-w]\t\tshow weak matches (mt<p-value<mt*10) in
angle brackets\n\t[-best]\t\tinclude only the best motif in diagrams
(hit_list mode only)\n\t[-seqp]\t\tuse SEQUENCE p-values for motif
thresholds\n\t\t\t(default: use POSITION p-values)\n\t[-mf <mf>]\tin
results use <mf> as motif file name\n\t[-df <df>]\tin results use <df> as
database name (ignored when -dblist specified)\n\t[-dl <dl>]\tin results
use <dl> as link to search sequence names (ignored when -dblist
specified)\n\t[-minseqs <ms>]\tlower bound on number of sequences in
db\n\t[-nostatus]\tdo not print progress report\n\t[-notext]\tdo not
generate text output\n\t[-nohtml]\tdo not generate html
output\n\t[-version]\tprint the version and exit\n\n', 'returncode': 1}
ERROR:root:MAST error: error at: -d

USAGE:
        mast    <motif file> <sequence file> [options]
        [-bfile <bf>]   read background frequencies from <bf>
        [-dblist]       the file specified as database contains a list of
databases
        [-o <dir>]      directory to output mast results
        [-oc <dir>]     directory to output mast results with overwriting
allowed
        [-hit_list]     print only a list of non-overlapping hits to stdout
        [-remcorr]      remove highly correlated motifs from query
        [-m <m>]+       use only motif(s) number <m> (overrides -mev)
        [-c <count>]    only use the first <count> motifs or all motifs
when <count> is zero (default: 0)
        [-mev <mev>]+   use only motifs with E-values less than <mev>
        [-diag <diag>]  nominal order and spacing of motifs
        [-norc]         do not score reverse complement DNA strand
        [-sep]          score reverse complement DNA strand as a separate
                        sequence
        [-dna]          translate DNA sequences to protein
        [-comp]         adjust p-values and E-values for sequence
composition
        [-ev <ev>]      print results for sequences with E-value < <ev>
                        (default: 10)
        [-mt <mt>]      show motif matches with p-value < mt (default:
0.0001)
        [-w]            show weak matches (mt<p-value<mt*10) in angle
brackets
        [-best]         include only the best motif in diagrams (hit_list
mode only)
        [-seqp]         use SEQUENCE p-values for motif thresholds
                        (default: use POSITION p-values)
        [-mf <mf>]      in results use <mf> as motif file name
        [-df <df>]      in results use <df> as database name (ignored when
-dblist specified)
        [-dl <dl>]      in results use <dl> as link to search sequence
names (ignored when -dblist specified)
        [-minseqs <ms>] lower bound on number of sequences in db
        [-nostatus]     do not print progress report
        [-notext]       do not generate text output
        [-nohtml]       do not generate html output
        [-version]      print the version and exit


ERROR


test_motif_scoring (iteration_test.IterationTest) ... WARNING:root:dropped
operon from network (max_operon_size exceeded): ['VNG1688C', 'VNG1689G',
'VNG1690G', 'VNG1691G', 'VNG1692G', 'VNG1693G', 'VNG1695G', 'VNG1697G',
'VNG1698G', 'VNG1699C', 'VNG1700G', 'VNG1701G', 'VNG1702G', 'VNG1703G',
'VNG1705G', 'VNG1706G', 'VNG1707G', 'VNG1709G', 'VNG1711G', 'VNG1713G',
'VNG1714G', 'VNG1715G', 'VNG1716G', 'VNG1718G', 'VNG1719G']
WARNING:root:25 genes not found in synonyms.
Unknown error in MAST:
  {'cmd': ['mast', '/tmp/meme.out.Yt7p_S', '-d', '/tmp/memeseqsPdzKEg',
'-bfile', '/tmp/memebgEn_cNt', '-nostatus', '-stdout', '-text', '-brief',
'-ev', '999999', '-mev', '9999999', '-mt', '0.99', '-seqp', '-remcorr'],
'output': 'error at: -d\n\nUSAGE:\n\tmast\t<motif file> <sequence file>
[options] \n\t[-bfile <bf>]\tread background frequencies from
<bf>\n\t[-dblist]\tthe file specified as database contains a list of
databases\n\t[-o <dir>]\tdirectory to output mast results\n\t[-oc
<dir>]\tdirectory to output mast results with overwriting
allowed\n\t[-hit_list]\tprint only a list of non-overlapping hits to
stdout\n\t[-remcorr]\tremove highly correlated motifs from query\n\t[-m
<m>]+\tuse only motif(s) number <m> (overrides -mev)\n\t[-c <count>]\tonly
use the first <count> motifs or all motifs when <count> is zero (default:
0)\n\t[-mev <mev>]+\tuse only motifs with E-values less than
<mev>\n\t[-diag <diag>]\tnominal order and spacing of
motifs\n\t[-norc]\t\tdo not score reverse complement DNA
strand\n\t[-sep]\t\tscore reverse complement DNA strand as a separate
\n\t\t\tsequence\n\t[-dna]\t\ttranslate DNA sequences to
protein\n\t[-comp]\t\tadjust p-values and E-values for sequence
composition\n\t[-ev <ev>]\tprint results for sequences with E-value <
<ev>\n\t\t\t(default: 10)\n\t[-mt <mt>]\tshow motif matches with p-value <
mt (default: 0.0001)\n\t[-w]\t\tshow weak matches (mt<p-value<mt*10) in
angle brackets\n\t[-best]\t\tinclude only the best motif in diagrams
(hit_list mode only)\n\t[-seqp]\t\tuse SEQUENCE p-values for motif
thresholds\n\t\t\t(default: use POSITION p-values)\n\t[-mf <mf>]\tin
results use <mf> as motif file name\n\t[-df <df>]\tin results use <df> as
database name (ignored when -dblist specified)\n\t[-dl <dl>]\tin results
use <dl> as link to search sequence names (ignored when -dblist
specified)\n\t[-minseqs <ms>]\tlower bound on number of sequences in
db\n\t[-nostatus]\tdo not print progress report\n\t[-notext]\tdo not
generate text output\n\t[-nohtml]\tdo not generate html
output\n\t[-version]\tprint the version and exit\n\n', 'returncode': 1}
ERROR:root:MAST error: error at: -d

USAGE:
        mast    <motif file> <sequence file> [options]
        [-bfile <bf>]   read background frequencies from <bf>
        [-dblist]       the file specified as database contains a list of
databases
        [-o <dir>]      directory to output mast results
        [-oc <dir>]     directory to output mast results with overwriting
allowed
        [-hit_list]     print only a list of non-overlapping hits to stdout
        [-remcorr]      remove highly correlated motifs from query
        [-m <m>]+       use only motif(s) number <m> (overrides -mev)
        [-c <count>]    only use the first <count> motifs or all motifs
when <count> is zero (default: 0)
        [-mev <mev>]+   use only motifs with E-values less than <mev>
        [-diag <diag>]  nominal order and spacing of motifs
        [-norc]         do not score reverse complement DNA strand
        [-sep]          score reverse complement DNA strand as a separate
                        sequence
        [-dna]          translate DNA sequences to protein
        [-comp]         adjust p-values and E-values for sequence
composition
        [-ev <ev>]      print results for sequences with E-value < <ev>
                        (default: 10)
        [-mt <mt>]      show motif matches with p-value < mt (default:
0.0001)
        [-w]            show weak matches (mt<p-value<mt*10) in angle
brackets
        [-best]         include only the best motif in diagrams (hit_list
mode only)
        [-seqp]         use SEQUENCE p-values for motif thresholds
                        (default: use POSITION p-values)
        [-mf <mf>]      in results use <mf> as motif file name
        [-df <df>]      in results use <df> as database name (ignored when
-dblist specified)
        [-dl <dl>]      in results use <dl> as link to search sequence
names (ignored when -dblist specified)
        [-minseqs <ms>] lower bound on number of sequences in db
        [-nostatus]     do not print progress report
        [-notext]       do not generate text output
        [-nohtml]       do not generate html output
        [-version]      print the version and exit


ERROR

======================================================================
ERROR: test_motif_scoring (meme430_test.Meme430Test)
tests the motif scoring in integration
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/autoxfs/aitchison/yeast/Aitchison
lab/sdanziger/Work/BSCM/cmonkey-python/test/meme430_test.py", line 76, in
test_motif_scoring
    matrix = func.compute(iteration_result)
  File "/nethome/sdanziger/Work/BSCM/cmonkey-python/cmonkey/motif.py", line
212, in compute
    return self.__compute(iteration_result, False, ref_matrix)
  File "/nethome/sdanziger/Work/BSCM/cmonkey-python/cmonkey/motif.py", line
240, in __compute
    num_motifs, force)
  File "/nethome/sdanziger/Work/BSCM/cmonkey-python/cmonkey/motif.py", line
378, in compute_pvalues
    _, pvalues, run_result = compute_cluster_score(params[cluster])
  File "/nethome/sdanziger/Work/BSCM/cmonkey-python/cmonkey/motif.py", line
447, in compute_cluster_score
    run_result = params.meme_runner(params)
  File "/nethome/sdanziger/Work/BSCM/cmonkey-python/cmonkey/meme.py", line
144, in __call__
    mast_output = self.mast(meme_outfile, dbfile, bgfile)
  File "/nethome/sdanziger/Work/BSCM/cmonkey-python/cmonkey/meme.py", line
261, in mast
    output = subprocess.check_output(command, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['mast', '/tmp/meme.out.JIecJE', '-d',
'/tmp/memeseqs56aAP5', '-bfile', '/tmp/memebgf1dj5o', '-nostatus',
'-stdout', '-text', '-brief', '-ev', '999999', '-mev', '9999999', '-mt',
'0.99', '-seqp', '-remcorr']' returned non-zero exit status 1

======================================================================
ERROR: test_motif_scoring (iteration_test.IterationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/autoxfs/aitchison/yeast/Aitchison
lab/sdanziger/Work/BSCM/cmonkey-python/test/iteration_test.py", line 136,
in test_motif_scoring
    motscores =
motif_scoring.compute(self.iteration_result).sorted_by_row_name()
  File "/nethome/sdanziger/Work/BSCM/cmonkey-python/cmonkey/motif.py", line
212, in compute
    return self.__compute(iteration_result, False, ref_matrix)
  File "/nethome/sdanziger/Work/BSCM/cmonkey-python/cmonkey/motif.py", line
240, in __compute
    num_motifs, force)
  File "/nethome/sdanziger/Work/BSCM/cmonkey-python/cmonkey/motif.py", line
378, in compute_pvalues
    _, pvalues, run_result = compute_cluster_score(params[cluster])
  File "/nethome/sdanziger/Work/BSCM/cmonkey-python/cmonkey/motif.py", line
447, in compute_cluster_score
    run_result = params.meme_runner(params)
  File "/nethome/sdanziger/Work/BSCM/cmonkey-python/cmonkey/meme.py", line
144, in __call__
    mast_output = self.mast(meme_outfile, dbfile, bgfile)
  File "/nethome/sdanziger/Work/BSCM/cmonkey-python/cmonkey/meme.py", line
261, in mast
    output = subprocess.check_output(command, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['mast', '/tmp/meme.out.Yt7p_S', '-d',
'/tmp/memeseqsPdzKEg', '-bfile', '/tmp/memebgEn_cNt', '-nostatus',
'-stdout', '-text', '-brief', '-ev', '999999', '-mev', '9999999', '-mt',
'0.99', '-seqp', '-remcorr']' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 161 tests in 35.395s

FAILED (errors=2)


On Wed, Feb 4, 2015 at 11:08 AM, Sam Danziger <sam.danziger@gmail.com>
wrote:

> Wei-ju,
>
> Sorry about that.  I don't know why it happened.  The file is still there
> so I must have un-indexed it somehow.
>
> -Sam
>
> On Wed, Feb 4, 2015 at 11:00 AM, Wei-ju Wu <notifications@github.com>
> wrote:
>
>> Hi Sam,
>> for some reason your commits removed the
>> testdata/RSAT_genomes_listing.txt file, which breaks the unit test suite. I
>> have put the file back into the repository. Please make sure the unit test
>> suite runs successfully before creating a merge request next time.
>> Thanks,
>> Wei-ju
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/baliga-lab/cmonkey2/pull/41#issuecomment-72915929>.
>>
>
>
>
> --
> Samuel A. Danziger, PhD
> Biomedical Engineering
> Sam_Danziger@ieee.org
> (908)246-4502
> http://samdanziger.com/
>
> Truth Cannot Contradict Truth
>



-- 
Samuel A. Danziger, PhD
Biomedical Engineering
Sam_Danziger@ieee.org
(908)246-4502
http://samdanziger.com/

Truth Cannot Contradict Truth

**Pull request merged**
